version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"  # API y servicios REST
      - "6334:6334"  # Web UI y monitoreo
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true        # Permite modo recuperación
      - QDRANT_FORCE_DISABLE_TELEMETRY=true    # Deshabilita telemetría
      - QDRANT_LOG_LEVEL=INFO                  # Nivel de logs
      # Configuración de memoria y rendimiento
      - QDRANT_MEMORY_LIMIT=512MB              # Límite de memoria
      - MALLOC_ARENA_MAX=2                     # Optimización de memoria
    restart: unless-stopped
    networks:
      - qdrant_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  init-qdrant:
    image: curlimages/curl
    depends_on:
      qdrant:
        condition: service_healthy
    command: >
      -X PUT "http://qdrant:6333/collections/knowledge_base" 
      -H "Content-Type: application/json" 
      -d '{
        "vectors": {
          "size": 8192,
          "distance": "Cosine"
        }
      }'

volumes:
  qdrant_storage:
    name: qdrant_storage

networks:
  qdrant_network:
    name: qdrant_network
    driver: bridge